//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputLayoutCodeGenerator
//     version 1.1.1
//     from "DualSenseGamepadHID" layout
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.InputSystem.Utilities;

// Suppress warnings from local variables for control references
// that we don't end up using.
#pragma warning disable CS0219

namespace UniSense
{
    public partial class FastDualSenseGamepadHID : UniSense.DualSenseGamepadHID
    {
        public const string metadata = "StickDeadzone;AxisDeadzone;Stick;Vector2;Button;Axis;Dpad;Vector3;DpadAxis;DiscreteButton;DualSenseGamepadHID;DualShockGamepad;Gamepad";
        public FastDualSenseGamepadHID()
        {
            var builder = this.Setup(49, 11, 8)
                .WithName("DualSenseGamepadHID")
                .WithDisplayName("PS5 Controller")
                .WithChildren(0, 25)
                .WithLayout(new InternedString("DualSenseGamepadHID"))
                .WithStateBlock(new InputStateBlock { format = new FourCC(1212761120), sizeInBits = 448 });

            var kStickLayout = new InternedString("Stick");
            var kButtonLayout = new InternedString("Button");
            var kDpadLayout = new InternedString("Dpad");
            var kVector3Layout = new InternedString("Vector3");
            var kAxisLayout = new InternedString("Axis");
            var kDpadAxisLayout = new InternedString("DpadAxis");
            var kDiscreteButtonLayout = new InternedString("DiscreteButton");

            // /DualSenseGamepadHID/leftStick
            var ctrlDualSenseGamepadHIDleftStick = Initialize_ctrlDualSenseGamepadHIDleftStick(kStickLayout, this);

            // /DualSenseGamepadHID/rightStick
            var ctrlDualSenseGamepadHIDrightStick = Initialize_ctrlDualSenseGamepadHIDrightStick(kStickLayout, this);

            // /DualSenseGamepadHID/leftTrigger
            var ctrlDualSenseGamepadHIDleftTrigger = Initialize_ctrlDualSenseGamepadHIDleftTrigger(kButtonLayout, this);

            // /DualSenseGamepadHID/rightTrigger
            var ctrlDualSenseGamepadHIDrightTrigger = Initialize_ctrlDualSenseGamepadHIDrightTrigger(kButtonLayout, this);

            // /DualSenseGamepadHID/dpad
            var ctrlDualSenseGamepadHIDdpad = Initialize_ctrlDualSenseGamepadHIDdpad(kDpadLayout, this);

            // /DualSenseGamepadHID/buttonWest
            var ctrlDualSenseGamepadHIDbuttonWest = Initialize_ctrlDualSenseGamepadHIDbuttonWest(kButtonLayout, this);

            // /DualSenseGamepadHID/buttonSouth
            var ctrlDualSenseGamepadHIDbuttonSouth = Initialize_ctrlDualSenseGamepadHIDbuttonSouth(kButtonLayout, this);

            // /DualSenseGamepadHID/buttonEast
            var ctrlDualSenseGamepadHIDbuttonEast = Initialize_ctrlDualSenseGamepadHIDbuttonEast(kButtonLayout, this);

            // /DualSenseGamepadHID/buttonNorth
            var ctrlDualSenseGamepadHIDbuttonNorth = Initialize_ctrlDualSenseGamepadHIDbuttonNorth(kButtonLayout, this);

            // /DualSenseGamepadHID/leftShoulder
            var ctrlDualSenseGamepadHIDleftShoulder = Initialize_ctrlDualSenseGamepadHIDleftShoulder(kButtonLayout, this);

            // /DualSenseGamepadHID/rightShoulder
            var ctrlDualSenseGamepadHIDrightShoulder = Initialize_ctrlDualSenseGamepadHIDrightShoulder(kButtonLayout, this);

            // /DualSenseGamepadHID/leftTriggerButton
            var ctrlDualSenseGamepadHIDleftTriggerButton = Initialize_ctrlDualSenseGamepadHIDleftTriggerButton(kButtonLayout, this);

            // /DualSenseGamepadHID/rightTriggerButton
            var ctrlDualSenseGamepadHIDrightTriggerButton = Initialize_ctrlDualSenseGamepadHIDrightTriggerButton(kButtonLayout, this);

            // /DualSenseGamepadHID/select
            var ctrlDualSenseGamepadHIDselect = Initialize_ctrlDualSenseGamepadHIDselect(kButtonLayout, this);

            // /DualSenseGamepadHID/start
            var ctrlDualSenseGamepadHIDstart = Initialize_ctrlDualSenseGamepadHIDstart(kButtonLayout, this);

            // /DualSenseGamepadHID/leftStickPress
            var ctrlDualSenseGamepadHIDleftStickPress = Initialize_ctrlDualSenseGamepadHIDleftStickPress(kButtonLayout, this);

            // /DualSenseGamepadHID/rightStickPress
            var ctrlDualSenseGamepadHIDrightStickPress = Initialize_ctrlDualSenseGamepadHIDrightStickPress(kButtonLayout, this);

            // /DualSenseGamepadHID/systemButton
            var ctrlDualSenseGamepadHIDsystemButton = Initialize_ctrlDualSenseGamepadHIDsystemButton(kButtonLayout, this);

            // /DualSenseGamepadHID/touchpadButton
            var ctrlDualSenseGamepadHIDtouchpadButton = Initialize_ctrlDualSenseGamepadHIDtouchpadButton(kButtonLayout, this);

            // /DualSenseGamepadHID/micMuteButton
            var ctrlDualSenseGamepadHIDmicMuteButton = Initialize_ctrlDualSenseGamepadHIDmicMuteButton(kButtonLayout, this);

            // /DualSenseGamepadHID/gyro
            var ctrlDualSenseGamepadHIDgyro = Initialize_ctrlDualSenseGamepadHIDgyro(kVector3Layout, this);

            // /DualSenseGamepadHID/accel
            var ctrlDualSenseGamepadHIDaccel = Initialize_ctrlDualSenseGamepadHIDaccel(kVector3Layout, this);

            // /DualSenseGamepadHID/batteryCharging
            var ctrlDualSenseGamepadHIDbatteryCharging = Initialize_ctrlDualSenseGamepadHIDbatteryCharging(kButtonLayout, this);

            // /DualSenseGamepadHID/batteryFullyCharged
            var ctrlDualSenseGamepadHIDbatteryFullyCharged = Initialize_ctrlDualSenseGamepadHIDbatteryFullyCharged(kButtonLayout, this);

            // /DualSenseGamepadHID/batteryLevel
            var ctrlDualSenseGamepadHIDbatteryLevel = Initialize_ctrlDualSenseGamepadHIDbatteryLevel(kAxisLayout, this);

            // /DualSenseGamepadHID/leftStick/up
            var ctrlDualSenseGamepadHIDleftStickup = Initialize_ctrlDualSenseGamepadHIDleftStickup(kButtonLayout, ctrlDualSenseGamepadHIDleftStick);

            // /DualSenseGamepadHID/leftStick/x
            var ctrlDualSenseGamepadHIDleftStickx = Initialize_ctrlDualSenseGamepadHIDleftStickx(kAxisLayout, ctrlDualSenseGamepadHIDleftStick);

            // /DualSenseGamepadHID/leftStick/y
            var ctrlDualSenseGamepadHIDleftSticky = Initialize_ctrlDualSenseGamepadHIDleftSticky(kAxisLayout, ctrlDualSenseGamepadHIDleftStick);

            // /DualSenseGamepadHID/leftStick/down
            var ctrlDualSenseGamepadHIDleftStickdown = Initialize_ctrlDualSenseGamepadHIDleftStickdown(kButtonLayout, ctrlDualSenseGamepadHIDleftStick);

            // /DualSenseGamepadHID/leftStick/left
            var ctrlDualSenseGamepadHIDleftStickleft = Initialize_ctrlDualSenseGamepadHIDleftStickleft(kButtonLayout, ctrlDualSenseGamepadHIDleftStick);

            // /DualSenseGamepadHID/leftStick/right
            var ctrlDualSenseGamepadHIDleftStickright = Initialize_ctrlDualSenseGamepadHIDleftStickright(kButtonLayout, ctrlDualSenseGamepadHIDleftStick);

            // /DualSenseGamepadHID/rightStick/up
            var ctrlDualSenseGamepadHIDrightStickup = Initialize_ctrlDualSenseGamepadHIDrightStickup(kButtonLayout, ctrlDualSenseGamepadHIDrightStick);

            // /DualSenseGamepadHID/rightStick/x
            var ctrlDualSenseGamepadHIDrightStickx = Initialize_ctrlDualSenseGamepadHIDrightStickx(kAxisLayout, ctrlDualSenseGamepadHIDrightStick);

            // /DualSenseGamepadHID/rightStick/y
            var ctrlDualSenseGamepadHIDrightSticky = Initialize_ctrlDualSenseGamepadHIDrightSticky(kAxisLayout, ctrlDualSenseGamepadHIDrightStick);

            // /DualSenseGamepadHID/rightStick/down
            var ctrlDualSenseGamepadHIDrightStickdown = Initialize_ctrlDualSenseGamepadHIDrightStickdown(kButtonLayout, ctrlDualSenseGamepadHIDrightStick);

            // /DualSenseGamepadHID/rightStick/left
            var ctrlDualSenseGamepadHIDrightStickleft = Initialize_ctrlDualSenseGamepadHIDrightStickleft(kButtonLayout, ctrlDualSenseGamepadHIDrightStick);

            // /DualSenseGamepadHID/rightStick/right
            var ctrlDualSenseGamepadHIDrightStickright = Initialize_ctrlDualSenseGamepadHIDrightStickright(kButtonLayout, ctrlDualSenseGamepadHIDrightStick);

            // /DualSenseGamepadHID/dpad/x
            var ctrlDualSenseGamepadHIDdpadx = Initialize_ctrlDualSenseGamepadHIDdpadx(kDpadAxisLayout, ctrlDualSenseGamepadHIDdpad);

            // /DualSenseGamepadHID/dpad/y
            var ctrlDualSenseGamepadHIDdpady = Initialize_ctrlDualSenseGamepadHIDdpady(kDpadAxisLayout, ctrlDualSenseGamepadHIDdpad);

            // /DualSenseGamepadHID/dpad/up
            var ctrlDualSenseGamepadHIDdpadup = Initialize_ctrlDualSenseGamepadHIDdpadup(kDiscreteButtonLayout, ctrlDualSenseGamepadHIDdpad);

            // /DualSenseGamepadHID/dpad/down
            var ctrlDualSenseGamepadHIDdpaddown = Initialize_ctrlDualSenseGamepadHIDdpaddown(kDiscreteButtonLayout, ctrlDualSenseGamepadHIDdpad);

            // /DualSenseGamepadHID/dpad/left
            var ctrlDualSenseGamepadHIDdpadleft = Initialize_ctrlDualSenseGamepadHIDdpadleft(kDiscreteButtonLayout, ctrlDualSenseGamepadHIDdpad);

            // /DualSenseGamepadHID/dpad/right
            var ctrlDualSenseGamepadHIDdpadright = Initialize_ctrlDualSenseGamepadHIDdpadright(kDiscreteButtonLayout, ctrlDualSenseGamepadHIDdpad);

            // /DualSenseGamepadHID/gyro/x
            var ctrlDualSenseGamepadHIDgyrox = Initialize_ctrlDualSenseGamepadHIDgyrox(kAxisLayout, ctrlDualSenseGamepadHIDgyro);

            // /DualSenseGamepadHID/gyro/y
            var ctrlDualSenseGamepadHIDgyroy = Initialize_ctrlDualSenseGamepadHIDgyroy(kAxisLayout, ctrlDualSenseGamepadHIDgyro);

            // /DualSenseGamepadHID/gyro/z
            var ctrlDualSenseGamepadHIDgyroz = Initialize_ctrlDualSenseGamepadHIDgyroz(kAxisLayout, ctrlDualSenseGamepadHIDgyro);

            // /DualSenseGamepadHID/accel/x
            var ctrlDualSenseGamepadHIDaccelx = Initialize_ctrlDualSenseGamepadHIDaccelx(kAxisLayout, ctrlDualSenseGamepadHIDaccel);

            // /DualSenseGamepadHID/accel/y
            var ctrlDualSenseGamepadHIDaccely = Initialize_ctrlDualSenseGamepadHIDaccely(kAxisLayout, ctrlDualSenseGamepadHIDaccel);

            // /DualSenseGamepadHID/accel/z
            var ctrlDualSenseGamepadHIDaccelz = Initialize_ctrlDualSenseGamepadHIDaccelz(kAxisLayout, ctrlDualSenseGamepadHIDaccel);

            // Usages.
            builder.WithControlUsage(0, new InternedString("Primary2DMotion"), ctrlDualSenseGamepadHIDleftStick);
            builder.WithControlUsage(1, new InternedString("Secondary2DMotion"), ctrlDualSenseGamepadHIDrightStick);
            builder.WithControlUsage(2, new InternedString("SecondaryTrigger"), ctrlDualSenseGamepadHIDleftTrigger);
            builder.WithControlUsage(3, new InternedString("SecondaryTrigger"), ctrlDualSenseGamepadHIDrightTrigger);
            builder.WithControlUsage(4, new InternedString("Hatswitch"), ctrlDualSenseGamepadHIDdpad);
            builder.WithControlUsage(5, new InternedString("SecondaryAction"), ctrlDualSenseGamepadHIDbuttonWest);
            builder.WithControlUsage(6, new InternedString("PrimaryAction"), ctrlDualSenseGamepadHIDbuttonSouth);
            builder.WithControlUsage(7, new InternedString("Submit"), ctrlDualSenseGamepadHIDbuttonSouth);
            builder.WithControlUsage(8, new InternedString("Back"), ctrlDualSenseGamepadHIDbuttonEast);
            builder.WithControlUsage(9, new InternedString("Cancel"), ctrlDualSenseGamepadHIDbuttonEast);
            builder.WithControlUsage(10, new InternedString("Menu"), ctrlDualSenseGamepadHIDstart);

            // Aliases.
            builder.WithControlAlias(0,  new InternedString("x"));
            builder.WithControlAlias(1,  new InternedString("square"));
            builder.WithControlAlias(2,  new InternedString("a"));
            builder.WithControlAlias(3,  new InternedString("cross"));
            builder.WithControlAlias(4,  new InternedString("b"));
            builder.WithControlAlias(5,  new InternedString("circle"));
            builder.WithControlAlias(6,  new InternedString("y"));
            builder.WithControlAlias(7,  new InternedString("triangle"));

            // Control getters/arrays.
            this.leftTriggerButton = ctrlDualSenseGamepadHIDleftTriggerButton;
            this.rightTriggerButton = ctrlDualSenseGamepadHIDrightTriggerButton;
            this.playStationButton = ctrlDualSenseGamepadHIDsystemButton;
            this.micMuteButton = ctrlDualSenseGamepadHIDmicMuteButton;
            this.touchpadButton = ctrlDualSenseGamepadHIDtouchpadButton;
            this.optionsButton = ctrlDualSenseGamepadHIDstart;
            this.shareButton = ctrlDualSenseGamepadHIDselect;
            this.L1 = ctrlDualSenseGamepadHIDleftShoulder;
            this.R1 = ctrlDualSenseGamepadHIDrightShoulder;
            this.L2 = ctrlDualSenseGamepadHIDleftTrigger;
            this.R2 = ctrlDualSenseGamepadHIDrightTrigger;
            this.L3 = ctrlDualSenseGamepadHIDleftStickPress;
            this.R3 = ctrlDualSenseGamepadHIDrightStickPress;
            this.buttonWest = ctrlDualSenseGamepadHIDbuttonWest;
            this.buttonNorth = ctrlDualSenseGamepadHIDbuttonNorth;
            this.buttonSouth = ctrlDualSenseGamepadHIDbuttonSouth;
            this.buttonEast = ctrlDualSenseGamepadHIDbuttonEast;
            this.leftStickButton = ctrlDualSenseGamepadHIDleftStickPress;
            this.rightStickButton = ctrlDualSenseGamepadHIDrightStickPress;
            this.startButton = ctrlDualSenseGamepadHIDstart;
            this.selectButton = ctrlDualSenseGamepadHIDselect;
            this.dpad = ctrlDualSenseGamepadHIDdpad;
            this.leftShoulder = ctrlDualSenseGamepadHIDleftShoulder;
            this.rightShoulder = ctrlDualSenseGamepadHIDrightShoulder;
            this.leftStick = ctrlDualSenseGamepadHIDleftStick;
            this.rightStick = ctrlDualSenseGamepadHIDrightStick;
            this.leftTrigger = ctrlDualSenseGamepadHIDleftTrigger;
            this.rightTrigger = ctrlDualSenseGamepadHIDrightTrigger;
            ctrlDualSenseGamepadHIDleftStick.up = ctrlDualSenseGamepadHIDleftStickup;
            ctrlDualSenseGamepadHIDleftStick.down = ctrlDualSenseGamepadHIDleftStickdown;
            ctrlDualSenseGamepadHIDleftStick.left = ctrlDualSenseGamepadHIDleftStickleft;
            ctrlDualSenseGamepadHIDleftStick.right = ctrlDualSenseGamepadHIDleftStickright;
            ctrlDualSenseGamepadHIDleftStick.x = ctrlDualSenseGamepadHIDleftStickx;
            ctrlDualSenseGamepadHIDleftStick.y = ctrlDualSenseGamepadHIDleftSticky;
            ctrlDualSenseGamepadHIDrightStick.up = ctrlDualSenseGamepadHIDrightStickup;
            ctrlDualSenseGamepadHIDrightStick.down = ctrlDualSenseGamepadHIDrightStickdown;
            ctrlDualSenseGamepadHIDrightStick.left = ctrlDualSenseGamepadHIDrightStickleft;
            ctrlDualSenseGamepadHIDrightStick.right = ctrlDualSenseGamepadHIDrightStickright;
            ctrlDualSenseGamepadHIDrightStick.x = ctrlDualSenseGamepadHIDrightStickx;
            ctrlDualSenseGamepadHIDrightStick.y = ctrlDualSenseGamepadHIDrightSticky;
            ctrlDualSenseGamepadHIDdpad.up = ctrlDualSenseGamepadHIDdpadup;
            ctrlDualSenseGamepadHIDdpad.down = ctrlDualSenseGamepadHIDdpaddown;
            ctrlDualSenseGamepadHIDdpad.left = ctrlDualSenseGamepadHIDdpadleft;
            ctrlDualSenseGamepadHIDdpad.right = ctrlDualSenseGamepadHIDdpadright;
            ctrlDualSenseGamepadHIDdpad.x = ctrlDualSenseGamepadHIDdpadx;
            ctrlDualSenseGamepadHIDdpad.y = ctrlDualSenseGamepadHIDdpady;
            ctrlDualSenseGamepadHIDgyro.x = ctrlDualSenseGamepadHIDgyrox;
            ctrlDualSenseGamepadHIDgyro.y = ctrlDualSenseGamepadHIDgyroy;
            ctrlDualSenseGamepadHIDgyro.z = ctrlDualSenseGamepadHIDgyroz;
            ctrlDualSenseGamepadHIDaccel.x = ctrlDualSenseGamepadHIDaccelx;
            ctrlDualSenseGamepadHIDaccel.y = ctrlDualSenseGamepadHIDaccely;
            ctrlDualSenseGamepadHIDaccel.z = ctrlDualSenseGamepadHIDaccelz;

            // State offset to control index map.
            builder.WithStateOffsetToControlIndexMap(new uint[]
            {
                4202522u, 4202525u, 4202526u, 8396825u, 8396827u, 8396828u, 12591136u, 12591139u, 12591140u, 16785439u
                , 16785441u, 16785442u, 20979714u, 25174019u, 33558565u, 33558566u, 33558567u, 33558568u, 33558569u, 33558570u
                , 35652613u, 36176902u, 36701191u, 37225480u, 37749769u, 38274058u, 38798347u, 39322636u, 39846925u, 40371214u
                , 40895503u, 41419792u, 41944081u, 42468370u, 42992659u, 67125291u, 75513900u, 83902509u, 92291118u, 100679727u
                , 109068336u, 228066326u, 230690840u, 233309207u
            });

            builder.Finish();
        }

        private UnityEngine.InputSystem.Controls.StickControl Initialize_ctrlDualSenseGamepadHIDleftStick(InternedString kStickLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStick = new UnityEngine.InputSystem.Controls.StickControl();
            ctrlDualSenseGamepadHIDleftStick.Setup()
                .At(this, 0)
                .WithParent(parent)
                .WithChildren(25, 6)
                .WithName("leftStick")
                .WithDisplayName("Left Stick")
                .WithShortDisplayName("LS")
                .WithLayout(kStickLayout)
                .WithUsages(0, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447244354),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithProcessor<InputProcessor<UnityEngine.Vector2>, UnityEngine.Vector2>(new UnityEngine.InputSystem.Processors.StickDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftStick;
        }

        private UnityEngine.InputSystem.Controls.StickControl Initialize_ctrlDualSenseGamepadHIDrightStick(InternedString kStickLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStick = new UnityEngine.InputSystem.Controls.StickControl();
            ctrlDualSenseGamepadHIDrightStick.Setup()
                .At(this, 1)
                .WithParent(parent)
                .WithChildren(31, 6)
                .WithName("rightStick")
                .WithDisplayName("Right Stick")
                .WithShortDisplayName("RS")
                .WithLayout(kStickLayout)
                .WithUsages(1, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447244354),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .WithProcessor<InputProcessor<UnityEngine.Vector2>, UnityEngine.Vector2>(new UnityEngine.InputSystem.Processors.StickDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightStick;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftTrigger(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftTrigger = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDleftTrigger.Setup()
                .At(this, 2)
                .WithParent(parent)
                .WithName("leftTrigger")
                .WithDisplayName("L2")
                .WithShortDisplayName("L2")
                .WithLayout(kButtonLayout)
                .WithUsages(2, 1)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 5,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDleftTrigger;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightTrigger(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightTrigger = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDrightTrigger.Setup()
                .At(this, 3)
                .WithParent(parent)
                .WithName("rightTrigger")
                .WithDisplayName("R2")
                .WithShortDisplayName("R2")
                .WithLayout(kButtonLayout)
                .WithUsages(3, 1)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 6,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDrightTrigger;
        }

        private UnityEngine.InputSystem.Controls.DpadControl Initialize_ctrlDualSenseGamepadHIDdpad(InternedString kDpadLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpad = new UnityEngine.InputSystem.Controls.DpadControl();
            ctrlDualSenseGamepadHIDdpad.Setup()
                .At(this, 4)
                .WithParent(parent)
                .WithChildren(37, 6)
                .WithName("dpad")
                .WithDisplayName("D-Pad")
                .WithLayout(kDpadLayout)
                .WithUsages(4, 1)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .WithDefaultState(8)
                .Finish();
            return ctrlDualSenseGamepadHIDdpad;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDbuttonWest(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbuttonWest = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDbuttonWest.Setup()
                .At(this, 5)
                .WithParent(parent)
                .WithName("buttonWest")
                .WithDisplayName("Square")
                .WithShortDisplayName("Square")
                .WithLayout(kButtonLayout)
                .WithUsages(5, 1)
                .WithAliases(0, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 4,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDbuttonWest;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDbuttonSouth(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbuttonSouth = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDbuttonSouth.Setup()
                .At(this, 6)
                .WithParent(parent)
                .WithName("buttonSouth")
                .WithDisplayName("Cross")
                .WithShortDisplayName("Cross")
                .WithLayout(kButtonLayout)
                .WithUsages(6, 2)
                .WithAliases(2, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 5,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDbuttonSouth;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDbuttonEast(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbuttonEast = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDbuttonEast.Setup()
                .At(this, 7)
                .WithParent(parent)
                .WithName("buttonEast")
                .WithDisplayName("Circle")
                .WithShortDisplayName("Circle")
                .WithLayout(kButtonLayout)
                .WithUsages(8, 2)
                .WithAliases(4, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 6,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDbuttonEast;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDbuttonNorth(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbuttonNorth = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDbuttonNorth.Setup()
                .At(this, 8)
                .WithParent(parent)
                .WithName("buttonNorth")
                .WithDisplayName("Triangle")
                .WithShortDisplayName("Triangle")
                .WithLayout(kButtonLayout)
                .WithAliases(6, 2)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 7,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDbuttonNorth;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftShoulder(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftShoulder = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDleftShoulder.Setup()
                .At(this, 9)
                .WithParent(parent)
                .WithName("leftShoulder")
                .WithDisplayName("L1")
                .WithShortDisplayName("L1")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDleftShoulder;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightShoulder(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightShoulder = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDrightShoulder.Setup()
                .At(this, 10)
                .WithParent(parent)
                .WithName("rightShoulder")
                .WithDisplayName("R1")
                .WithShortDisplayName("R1")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 1,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDrightShoulder;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftTriggerButton(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftTriggerButton = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDleftTriggerButton.Setup()
                .At(this, 11)
                .WithParent(parent)
                .WithName("leftTriggerButton")
                .WithDisplayName("leftTriggerButton")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 2,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDleftTriggerButton;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightTriggerButton(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightTriggerButton = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDrightTriggerButton.Setup()
                .At(this, 12)
                .WithParent(parent)
                .WithName("rightTriggerButton")
                .WithDisplayName("rightTriggerButton")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 3,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDrightTriggerButton;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDselect(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDselect = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDselect.Setup()
                .At(this, 13)
                .WithParent(parent)
                .WithName("select")
                .WithDisplayName("Share")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 4,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDselect;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDstart(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDstart = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDstart.Setup()
                .At(this, 14)
                .WithParent(parent)
                .WithName("start")
                .WithDisplayName("Options")
                .WithLayout(kButtonLayout)
                .WithUsages(10, 1)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 5,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDstart;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftStickPress(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStickPress = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDleftStickPress.Setup()
                .At(this, 15)
                .WithParent(parent)
                .WithName("leftStickPress")
                .WithDisplayName("L3")
                .WithShortDisplayName("L3")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 6,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDleftStickPress;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightStickPress(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStickPress = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDrightStickPress.Setup()
                .At(this, 16)
                .WithParent(parent)
                .WithName("rightStickPress")
                .WithDisplayName("R3")
                .WithShortDisplayName("R3")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 9,
                    bitOffset = 7,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDrightStickPress;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDsystemButton(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDsystemButton = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDsystemButton.Setup()
                .At(this, 17)
                .WithParent(parent)
                .WithName("systemButton")
                .WithDisplayName("System")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 10,
                    bitOffset = 0,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDsystemButton;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDtouchpadButton(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDtouchpadButton = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDtouchpadButton.Setup()
                .At(this, 18)
                .WithParent(parent)
                .WithName("touchpadButton")
                .WithDisplayName("Touchpad Press")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 10,
                    bitOffset = 1,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDtouchpadButton;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDmicMuteButton(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDmicMuteButton = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDmicMuteButton.Setup()
                .At(this, 19)
                .WithParent(parent)
                .WithName("micMuteButton")
                .WithDisplayName("Mic Mute")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 10,
                    bitOffset = 2,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDmicMuteButton;
        }

        private UnityEngine.InputSystem.Controls.Vector3Control Initialize_ctrlDualSenseGamepadHIDgyro(InternedString kVector3Layout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDgyro = new UnityEngine.InputSystem.Controls.Vector3Control();
            ctrlDualSenseGamepadHIDgyro.Setup()
                .At(this, 20)
                .WithParent(parent)
                .WithChildren(43, 3)
                .WithName("gyro")
                .WithDisplayName("gyro")
                .WithLayout(kVector3Layout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447244627),
                    byteOffset = 16,
                    bitOffset = 0,
                    sizeInBits = 48
                })
                .Finish();
            return ctrlDualSenseGamepadHIDgyro;
        }

        private UnityEngine.InputSystem.Controls.Vector3Control Initialize_ctrlDualSenseGamepadHIDaccel(InternedString kVector3Layout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDaccel = new UnityEngine.InputSystem.Controls.Vector3Control();
            ctrlDualSenseGamepadHIDaccel.Setup()
                .At(this, 21)
                .WithParent(parent)
                .WithChildren(46, 3)
                .WithName("accel")
                .WithDisplayName("accel")
                .WithLayout(kVector3Layout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1447244627),
                    byteOffset = 22,
                    bitOffset = 0,
                    sizeInBits = 48
                })
                .Finish();
            return ctrlDualSenseGamepadHIDaccel;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDbatteryCharging(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbatteryCharging = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDbatteryCharging.Setup()
                .At(this, 22)
                .WithParent(parent)
                .WithName("batteryCharging")
                .WithDisplayName("Battery is Charging")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 54,
                    bitOffset = 3,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDbatteryCharging;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDbatteryFullyCharged(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbatteryFullyCharged = new UnityEngine.InputSystem.Controls.ButtonControl();
            ctrlDualSenseGamepadHIDbatteryFullyCharged.Setup()
                .At(this, 23)
                .WithParent(parent)
                .WithName("batteryFullyCharged")
                .WithDisplayName("Battery is Fully Charged")
                .WithLayout(kButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 55,
                    bitOffset = 5,
                    sizeInBits = 1
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDbatteryFullyCharged;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDbatteryLevel(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDbatteryLevel = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMax = 1f };
            ctrlDualSenseGamepadHIDbatteryLevel.Setup()
                .At(this, 24)
                .WithParent(parent)
                .WithName("batteryLevel")
                .WithDisplayName("Battery Level")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 55,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .Finish();
            return ctrlDualSenseGamepadHIDbatteryLevel;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftStickup(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStickup = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 0.5f, invert = true, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDleftStickup.Setup()
                .At(this, 25)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("Left Stick Up")
                .WithShortDisplayName("LS Up")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 2,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftStickup;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDleftStickx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStickx = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDleftStickx.Setup()
                .At(this, 26)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Left Stick X")
                .WithShortDisplayName("LS X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftStickx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDleftSticky(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftSticky = new UnityEngine.InputSystem.Controls.AxisControl { invert = true, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDleftSticky.Setup()
                .At(this, 27)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Left Stick Y")
                .WithShortDisplayName("LS Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 2,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftSticky;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftStickdown(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStickdown = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = 0.5f, clampMax = 1f, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDleftStickdown.Setup()
                .At(this, 28)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("Left Stick Down")
                .WithShortDisplayName("LS Down")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 2,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftStickdown;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftStickleft(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStickleft = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 0.5f, invert = true, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDleftStickleft.Setup()
                .At(this, 29)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("Left Stick Left")
                .WithShortDisplayName("LS Left")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftStickleft;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDleftStickright(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDleftStickright = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = 0.5f, clampMax = 1f, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDleftStickright.Setup()
                .At(this, 30)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("Left Stick Right")
                .WithShortDisplayName("LS Right")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 1,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDleftStickright;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightStickup(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStickup = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 0.5f, invert = true, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDrightStickup.Setup()
                .At(this, 31)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("Right Stick Up")
                .WithShortDisplayName("RS Up")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 4,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightStickup;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDrightStickx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStickx = new UnityEngine.InputSystem.Controls.AxisControl { normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDrightStickx.Setup()
                .At(this, 32)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("Right Stick X")
                .WithShortDisplayName("RS X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightStickx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDrightSticky(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightSticky = new UnityEngine.InputSystem.Controls.AxisControl { invert = true, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDrightSticky.Setup()
                .At(this, 33)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("Right Stick Y")
                .WithShortDisplayName("RS Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 4,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(-1, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightSticky;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightStickdown(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStickdown = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = 0.5f, clampMax = 1f, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDrightStickdown.Setup()
                .At(this, 34)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("Right Stick Down")
                .WithShortDisplayName("RS Down")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 4,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightStickdown;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightStickleft(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStickleft = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMax = 0.5f, invert = true, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDrightStickleft.Setup()
                .At(this, 35)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("Right Stick Left")
                .WithShortDisplayName("RS Left")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightStickleft;
        }

        private UnityEngine.InputSystem.Controls.ButtonControl Initialize_ctrlDualSenseGamepadHIDrightStickright(InternedString kButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDrightStickright = new UnityEngine.InputSystem.Controls.ButtonControl { clamp = UnityEngine.InputSystem.Controls.AxisControl.Clamp.BeforeNormalize, clampMin = 0.5f, clampMax = 1f, normalize = true, normalizeMax = 1f, normalizeZero = 0.5f };
            ctrlDualSenseGamepadHIDrightStickright.Setup()
                .At(this, 36)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("Right Stick Right")
                .WithShortDisplayName("RS Right")
                .WithLayout(kButtonLayout)
                .IsSynthetic(true)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1113150533),
                    byteOffset = 3,
                    bitOffset = 0,
                    sizeInBits = 8
                })
                .WithDefaultState(127)
                .WithMinAndMax(0, 1)
                .WithProcessor<InputProcessor<System.Single>, System.Single>(new UnityEngine.InputSystem.Processors.AxisDeadzoneProcessor())
                .Finish();
            return ctrlDualSenseGamepadHIDrightStickright;
        }

        private UnityEngine.InputSystem.Controls.DpadControl.DpadAxisControl Initialize_ctrlDualSenseGamepadHIDdpadx(InternedString kDpadAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpadx = new UnityEngine.InputSystem.Controls.DpadControl.DpadAxisControl();
            ctrlDualSenseGamepadHIDdpadx.Setup()
                .At(this, 37)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("D-Pad X")
                .WithShortDisplayName("D-Pad X")
                .WithLayout(kDpadAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .Finish();
            ctrlDualSenseGamepadHIDdpadx.component = 0;
            return ctrlDualSenseGamepadHIDdpadx;
        }

        private UnityEngine.InputSystem.Controls.DpadControl.DpadAxisControl Initialize_ctrlDualSenseGamepadHIDdpady(InternedString kDpadAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpady = new UnityEngine.InputSystem.Controls.DpadControl.DpadAxisControl();
            ctrlDualSenseGamepadHIDdpady.Setup()
                .At(this, 38)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("D-Pad Y")
                .WithShortDisplayName("D-Pad Y")
                .WithLayout(kDpadAxisLayout)
                .IsSynthetic(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .Finish();
            ctrlDualSenseGamepadHIDdpady.component = 1;
            return ctrlDualSenseGamepadHIDdpady;
        }

        private UnityEngine.InputSystem.Controls.DiscreteButtonControl Initialize_ctrlDualSenseGamepadHIDdpadup(InternedString kDiscreteButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpadup = new UnityEngine.InputSystem.Controls.DiscreteButtonControl { minValue = 7, maxValue = 1, wrapAtValue = 7, nullValue = 8 };
            ctrlDualSenseGamepadHIDdpadup.Setup()
                .At(this, 39)
                .WithParent(parent)
                .WithName("up")
                .WithDisplayName("D-Pad Up")
                .WithShortDisplayName("D-Pad Up")
                .WithLayout(kDiscreteButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDdpadup;
        }

        private UnityEngine.InputSystem.Controls.DiscreteButtonControl Initialize_ctrlDualSenseGamepadHIDdpaddown(InternedString kDiscreteButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpaddown = new UnityEngine.InputSystem.Controls.DiscreteButtonControl { minValue = 3, maxValue = 5 };
            ctrlDualSenseGamepadHIDdpaddown.Setup()
                .At(this, 40)
                .WithParent(parent)
                .WithName("down")
                .WithDisplayName("D-Pad Down")
                .WithShortDisplayName("D-Pad Down")
                .WithLayout(kDiscreteButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDdpaddown;
        }

        private UnityEngine.InputSystem.Controls.DiscreteButtonControl Initialize_ctrlDualSenseGamepadHIDdpadleft(InternedString kDiscreteButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpadleft = new UnityEngine.InputSystem.Controls.DiscreteButtonControl { minValue = 5, maxValue = 7 };
            ctrlDualSenseGamepadHIDdpadleft.Setup()
                .At(this, 41)
                .WithParent(parent)
                .WithName("left")
                .WithDisplayName("D-Pad Left")
                .WithShortDisplayName("D-Pad Left")
                .WithLayout(kDiscreteButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDdpadleft;
        }

        private UnityEngine.InputSystem.Controls.DiscreteButtonControl Initialize_ctrlDualSenseGamepadHIDdpadright(InternedString kDiscreteButtonLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDdpadright = new UnityEngine.InputSystem.Controls.DiscreteButtonControl { minValue = 1, maxValue = 3 };
            ctrlDualSenseGamepadHIDdpadright.Setup()
                .At(this, 42)
                .WithParent(parent)
                .WithName("right")
                .WithDisplayName("D-Pad Right")
                .WithShortDisplayName("D-Pad Right")
                .WithLayout(kDiscreteButtonLayout)
                .IsButton(true)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1112101920),
                    byteOffset = 8,
                    bitOffset = 0,
                    sizeInBits = 4
                })
                .WithMinAndMax(0, 1)
                .Finish();
            return ctrlDualSenseGamepadHIDdpadright;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDgyrox(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDgyrox = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlDualSenseGamepadHIDgyrox.Setup()
                .At(this, 43)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("gyro X")
                .WithShortDisplayName("gyro X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 16,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlDualSenseGamepadHIDgyrox;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDgyroy(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDgyroy = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlDualSenseGamepadHIDgyroy.Setup()
                .At(this, 44)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("gyro Y")
                .WithShortDisplayName("gyro Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 18,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlDualSenseGamepadHIDgyroy;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDgyroz(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDgyroz = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlDualSenseGamepadHIDgyroz.Setup()
                .At(this, 45)
                .WithParent(parent)
                .WithName("z")
                .WithDisplayName("gyro Z")
                .WithShortDisplayName("gyro Z")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 20,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlDualSenseGamepadHIDgyroz;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDaccelx(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDaccelx = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlDualSenseGamepadHIDaccelx.Setup()
                .At(this, 46)
                .WithParent(parent)
                .WithName("x")
                .WithDisplayName("accel X")
                .WithShortDisplayName("accel X")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 22,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlDualSenseGamepadHIDaccelx;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDaccely(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDaccely = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlDualSenseGamepadHIDaccely.Setup()
                .At(this, 47)
                .WithParent(parent)
                .WithName("y")
                .WithDisplayName("accel Y")
                .WithShortDisplayName("accel Y")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 24,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlDualSenseGamepadHIDaccely;
        }

        private UnityEngine.InputSystem.Controls.AxisControl Initialize_ctrlDualSenseGamepadHIDaccelz(InternedString kAxisLayout, InputControl parent)
        {
            var ctrlDualSenseGamepadHIDaccelz = new UnityEngine.InputSystem.Controls.AxisControl();
            ctrlDualSenseGamepadHIDaccelz.Setup()
                .At(this, 48)
                .WithParent(parent)
                .WithName("z")
                .WithDisplayName("accel Z")
                .WithShortDisplayName("accel Z")
                .WithLayout(kAxisLayout)
                .WithStateBlock(new InputStateBlock
                {
                    format = new FourCC(1397248596),
                    byteOffset = 26,
                    bitOffset = 0,
                    sizeInBits = 16
                })
                .Finish();
            return ctrlDualSenseGamepadHIDaccelz;
        }
    }
}
